name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ./backend

            git pull origin main

            npx prisma db push

            npm install --lockfile

            npm run build

            pm2 restart backend --silent

            echo "Deployment successful"
